### ISSUE TITLE
Missing MatAppearance image in user guide

### ISSUE THREAD

**Issue by tontonbibi** [outpaycelab/outpayce-checkout-sdk-web#7]
Hello,

MatAppearance image url is not working in user guide.
![Screenshot 2024-10-14 at 15 39 30](https://github.com/user-attachments/assets/d732fe84-89b6-4255-94b6-64cdcf290c46)

https://github.com/outpaycelab/outpayce-checkout-sdk-web/blob/main/doc/img/matappearance.png -> 404 not found

**Comment by tferhat-outpayce** [comment]
The missing image has been added.  The issue will be closed if no other questions. Please open a new issue if needed.
